package report

import "github.com/nguyenquocanhz/diagward/model"

// labels are the fixed words of every renderer, in both languages.
var labels = map[string]model.Text{
	"title":       model.T("Server hardware report", "Báo cáo phần cứng máy chủ"),
	"host":        model.T("Server", "Máy chủ"),
	"model":       model.T("Vendor / model", "Hãng / model"),
	"serialTag":   model.T("Serial / service tag", "Serial / service tag"),
	"os":          model.T("Operating system", "Hệ điều hành"),
	"kernel":      model.T("Kernel / build", "Kernel / build"),
	"cpu":         model.T("CPU", "CPU"),
	"ram":         model.T("Memory", "RAM"),
	"board":       model.T("Mainboard", "Mainboard"),
	"bios":        model.T("BIOS", "BIOS"),
	"bmcAddr":     model.T("BMC", "BMC"),
	"uptime":      model.T("Uptime", "Uptime"),
	"virtual":     model.T("Virtual machine", "Máy ảo"),
	"privilege":   model.T("Ran as", "Quyền chạy"),
	"privRoot":    model.T("root / Administrator (complete)", "root / Administrator (đầy đủ)"),
	"privUser":    model.T("normal user (some checks skipped)", "người dùng thường (một số mục bị bỏ qua)"),
	"collected":   model.T("Collected at", "Thời điểm thu thập"),
	"duration":    model.T("Collection took", "Thời gian thu thập"),
	"components":  model.T("Components", "Các nhóm linh kiện"),
	"findings":    model.T("Problems found", "Vấn đề phát hiện"),
	"noFindings":  model.T("No problems were found in the checks that ran.", "Không phát hiện vấn đề nào trong các mục đã kiểm tra."),
	"okChecked":   model.T("Checked and healthy", "Đã kiểm tra, ổn"),
	"action":      model.T("What to do", "Cách xử lý"),
	"evidence":    model.T("Evidence", "Bằng chứng"),
	"doNow":       model.T("Do this now", "Cần làm ngay"),
	"doNowEmpty":  model.T("Nothing urgent. Keep monitoring and run Diagward again after any hardware change.", "Không có việc gì gấp. Tiếp tục theo dõi và chạy lại Diagward sau mỗi lần thay đổi phần cứng."),
	"parts":       model.T("Parts to replace", "Linh kiện cần thay"),
	"partsSub":    model.T("for the warranty / RMA case", "dùng khi mở ca bảo hành / RMA"),
	"partKind":    model.T("Part", "Linh kiện"),
	"vendorModel": model.T("Vendor / model", "Hãng / model"),
	"serial":      model.T("Serial", "Serial"),
	"location":    model.T("Location", "Vị trí"),
	"firmware":    model.T("Firmware", "Firmware"),
	"why":         model.T("Reason", "Lý do"),
	"copyText":    model.T("Copy as text", "Sao chép dạng văn bản"),
	"copy":        model.T("Copy", "Sao chép"),
	"copied":      model.T("Copied", "Đã sao chép"),
	"notChecked":  model.T("Not fully checked", "Chưa kiểm tra đầy đủ"),
	"coverage":    model.T("What was checked", "Phạm vi kiểm tra"),
	"covFailed":   model.T("Check failed", "Kiểm tra bị lỗi"),
	"covPartial":  model.T("Partly checked", "Kiểm tra một phần"),
	"covSkipped":  model.T("Skipped", "Bỏ qua"),
	"covRan":      model.T("Checked", "Đã kiểm tra"),
	"compPartial": model.T("partly checked", "kiểm tra một phần"),
	"notes":       model.T("Notes", "Ghi chú"),
	"tables":      model.T("Inventory and measurements", "Chi tiết kiểm kê và số đo"),
	"status":      model.T("Status", "Trạng thái"),
	"generated":   model.T("Generated by", "Tạo bởi"),
	"verboseHint": model.T("More detail (tables, evidence): add -v", "Xem chi tiết (bảng, bằng chứng): thêm -v"),
	"htmlHint":    model.T("HTML report to send or print: add --html report.html", "Báo cáo HTML để gửi hoặc in: thêm --html report.html"),
	"langHint":    model.T("Vietnamese: add --lang vi", "English: thêm --lang en"),
	"none":        model.T("none", "không có"),
	"more":        model.T("more", "nữa"),
	"copySummary": model.T("Copy summary", "Copy tóm tắt"),
	"print":       model.T("Print / PDF", "In / PDF"),
	"sysInfo":     model.T("System info", "Thông tin máy"),
	"statCrit":    model.T("critical", "nghiêm trọng"),
	"statWarn":    model.T("warnings", "cảnh báo"),
	"statNote":    model.T("notes", "lưu ý"),
	"statChecked": model.T("checked", "đã kiểm"),
}

func label(k string) model.Text {
	if t, ok := labels[k]; ok {
		return t
	}
	return model.T(k, k)
}

func covLabel(state string) model.Text {
	switch state {
	case model.CovFailed:
		return label("covFailed")
	case model.CovPartial:
		return label("covPartial")
	case model.CovSkipped:
		return label("covSkipped")
	}
	return label("covRan")
}
